# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'againtry.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 833)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1121, 811))
        self.tabWidget.setStyleSheet("QTabWidget::pane{border: 1px solid grey;background-image:url(云.jpg);}" + \
                                     "QTabBar::tab{min-width:95px;min-height:45px;background:transparent;}" + \
                                     "QTabBar::tab{font:9pt \"黑体\";}" + \
                                     "QTabBar::tab:selected{color:white;background-color:rgb(0, 85, 127);}" + \
                                     "QTabBar::tab:!selected{color: black;background:transparent;}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_1 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_1.setGeometry(QtCore.QRect(60, 70, 221, 441))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setStyleSheet("font: 11pt \"黑体\";")
        self.groupBox_1.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_1.setObjectName("groupBox_1")
        self.start_but = QtWidgets.QPushButton(self.groupBox_1)
        self.start_but.setGeometry(QtCore.QRect(50, 50, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start_but.setFont(font)
        self.start_but.setStyleSheet("font: 11pt \"Arial\";\n"
"")
        self.start_but.setObjectName("start_but")
        self.stop_but = QtWidgets.QPushButton(self.groupBox_1)
        self.stop_but.setGeometry(QtCore.QRect(50, 190, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stop_but.setFont(font)
        self.stop_but.setStyleSheet("font: 11pt \"Arial\";")
        self.stop_but.setObjectName("stop_but")
        self.play_but = QtWidgets.QPushButton(self.groupBox_1)
        self.play_but.setGeometry(QtCore.QRect(50, 330, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.play_but.setFont(font)
        self.play_but.setStyleSheet("font: 11pt \"Arial\";")
        self.play_but.setObjectName("play_but")
        self.keyword_but = QtWidgets.QPushButton(self.tab)
        self.keyword_but.setGeometry(QtCore.QRect(110, 610, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.keyword_but.setFont(font)
        self.keyword_but.setObjectName("keyword_but")
        self.status_label = QtWidgets.QLabel(self.tab)
        self.status_label.setGeometry(QtCore.QRect(10, 730, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 570, 221, 141))
        self.groupBox_2.setStyleSheet("font: 11pt \"黑体\";")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(360, 10, 691, 741))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.sentence_box = QtWidgets.QTextBrowser(self.groupBox)
        self.sentence_box.setGeometry(QtCore.QRect(20, 20, 651, 521))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.sentence_box.setFont(font)
        self.sentence_box.setReadOnly(False)
        self.sentence_box.setObjectName("sentence_box")
        self.keyword_box = QtWidgets.QTextBrowser(self.groupBox)
        self.keyword_box.setGeometry(QtCore.QRect(20, 580, 651, 141))
        self.keyword_box.setObjectName("keyword_box")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.status_label_2 = QtWidgets.QLabel(self.tab_2)
        self.status_label_2.setGeometry(QtCore.QRect(10, 730, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.status_label_2.setFont(font)
        self.status_label_2.setObjectName("status_label_2")
        self.keyword_but_2 = QtWidgets.QPushButton(self.tab_2)
        self.keyword_but_2.setGeometry(QtCore.QRect(110, 610, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.keyword_but_2.setFont(font)
        self.keyword_but_2.setObjectName("keyword_but_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(360, 10, 691, 741))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.sentence_box_2 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.sentence_box_2.setGeometry(QtCore.QRect(20, 20, 651, 521))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.sentence_box_2.setFont(font)
        self.sentence_box_2.setReadOnly(False)
        self.sentence_box_2.setObjectName("sentence_box_2")
        self.keyword_box_2 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.keyword_box_2.setGeometry(QtCore.QRect(20, 580, 651, 141))
        self.keyword_box_2.setObjectName("keyword_box_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(60, 70, 221, 441))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("font: 11pt \"黑体\";")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.start_but_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.start_but_2.setGeometry(QtCore.QRect(50, 50, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start_but_2.setFont(font)
        self.start_but_2.setStyleSheet("font: 11pt \"Arial\";\n"
"")
        self.start_but_2.setObjectName("start_but_2")
        self.stop_but_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.stop_but_2.setGeometry(QtCore.QRect(50, 190, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stop_but_2.setFont(font)
        self.stop_but_2.setStyleSheet("font: 11pt \"Arial\";")
        self.stop_but_2.setObjectName("stop_but_2")
        self.play_but_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.play_but_2.setGeometry(QtCore.QRect(50, 330, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.play_but_2.setFont(font)
        self.play_but_2.setStyleSheet("font: 11pt \"Arial\";")
        self.play_but_2.setObjectName("play_but_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(60, 570, 221, 141))
        self.groupBox_6.setStyleSheet("font: 11pt \"黑体\";")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_6.raise_()
        self.status_label_2.raise_()
        self.keyword_but_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_1.setTitle(_translate("MainWindow", "实时语音转写"))
        self.start_but.setText(_translate("MainWindow", "start"))
        self.stop_but.setText(_translate("MainWindow", "stop"))
        self.play_but.setText(_translate("MainWindow", "playback"))
        self.keyword_but.setText(_translate("MainWindow", "keyword"))
        self.status_label.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "关键词提取"))
        self.sentence_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt; font-weight:400;\"><br /></p></body></html>"))
        self.keyword_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt; font-weight:400;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "讯飞接口"))
        self.status_label_2.setText(_translate("MainWindow", "TextLabel"))
        self.keyword_but_2.setText(_translate("MainWindow", "keyword"))
        self.sentence_box_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt; font-weight:400;\"><br /></p></body></html>"))
        self.keyword_box_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt; font-weight:400;\"><br /></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "实时语音转写"))
        self.start_but_2.setText(_translate("MainWindow", "start"))
        self.stop_but_2.setText(_translate("MainWindow", "stop"))
        self.play_but_2.setText(_translate("MainWindow", "playback"))
        self.groupBox_6.setTitle(_translate("MainWindow", "关键词提取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "自主模型"))

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())