# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blochin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 873)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1121, 861))
        self.tabWidget.setStyleSheet("QTabWidget::pane{border: 1px solid grey;background-image:url(云.jpg);}" + \
                                     "QTabBar::tab{min-width:95px;min-height:45px;background:transparent;}" + \
                                     "QTabBar::tab{font:9pt \"黑体\";}" + \
                                     "QTabBar::tab:selected{color:white;background-color:rgb(0, 85, 127);}" + \
                                     "QTabBar::tab:!selected{color: black;background:transparent;}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(280, 60, 661, 511))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.sentence_box = QtWidgets.QTextBrowser(self.groupBox)
        self.sentence_box.setGeometry(QtCore.QRect(20, 20, 621, 311))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sentence_box.setFont(font)
        self.sentence_box.setReadOnly(False)
        self.sentence_box.setObjectName("sentence_box")
        self.keyword_box = QtWidgets.QTextBrowser(self.groupBox)
        self.keyword_box.setGeometry(QtCore.QRect(20, 360, 621, 131))
        self.keyword_box.setObjectName("keyword_box")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(40, 370, 181, 121))
        self.groupBox_1.setStyleSheet("font: 10pt \"黑体\";")
        self.groupBox_1.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_1.setObjectName("groupBox_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 600, 661, 221))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 510, 181, 281))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("font: 10pt \"黑体\";")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.mine_but = QtWidgets.QPushButton(self.groupBox_3)
        self.mine_but.setGeometry(QtCore.QRect(40, 40, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mine_but.setFont(font)
        self.mine_but.setStyleSheet("font: 9pt \"黑体\";\n"
"")
        self.mine_but.setObjectName("mine_but")
        self.add_but = QtWidgets.QPushButton(self.groupBox_3)
        self.add_but.setGeometry(QtCore.QRect(40, 120, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.add_but.setFont(font)
        self.add_but.setStyleSheet("font: 9pt \"黑体\";")
        self.add_but.setObjectName("add_but")
        self.inquire_but = QtWidgets.QPushButton(self.groupBox_3)
        self.inquire_but.setGeometry(QtCore.QRect(40, 200, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.inquire_but.setFont(font)
        self.inquire_but.setStyleSheet("font: 9pt \"黑体\";")
        self.inquire_but.setObjectName("inquire_but")
        self.status_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.status_label_3.setGeometry(QtCore.QRect(20, 810, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.status_label_3.setFont(font)
        self.status_label_3.setStyleSheet("font: 9pt \"Arial\";")
        self.status_label_3.setObjectName("status_label_3")
        self.blockchain_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.blockchain_box.setGeometry(QtCore.QRect(300, 620, 621, 181))
        self.blockchain_box.setObjectName("blockchain_box")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 70, 181, 281))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("font: 10pt \"黑体\";")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.start_but = QtWidgets.QPushButton(self.groupBox_4)
        self.start_but.setGeometry(QtCore.QRect(40, 40, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start_but.setFont(font)
        self.start_but.setStyleSheet("font: 10pt \"Arial\";\n"
"")
        self.start_but.setObjectName("start_but")
        self.stop_but = QtWidgets.QPushButton(self.groupBox_4)
        self.stop_but.setGeometry(QtCore.QRect(40, 120, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stop_but.setFont(font)
        self.stop_but.setStyleSheet("font: 10pt \"Arial\";")
        self.stop_but.setObjectName("stop_but")
        self.play_but = QtWidgets.QPushButton(self.groupBox_4)
        self.play_but.setGeometry(QtCore.QRect(40, 200, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.play_but.setFont(font)
        self.play_but.setStyleSheet("font: 10pt \"Arial\";")
        self.play_but.setObjectName("play_but")
        self.keyword_but = QtWidgets.QPushButton(self.centralwidget)
        self.keyword_but.setGeometry(QtCore.QRect(80, 410, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.keyword_but.setFont(font)
        self.keyword_but.setStyleSheet("font: 10pt \"Arial\";")
        self.keyword_but.setObjectName("keyword_but")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "讯飞接口"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "自主模型"))
        self.sentence_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt;\"><br /></p></body></html>"))
        self.keyword_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.groupBox_1.setTitle(_translate("MainWindow", "关键词提取"))
        self.groupBox_3.setTitle(_translate("MainWindow", "区块链"))
        self.mine_but.setText(_translate("MainWindow", "挖矿"))
        self.add_but.setText(_translate("MainWindow", "添加交易"))
        self.inquire_but.setText(_translate("MainWindow", "查询信息"))
        self.status_label_3.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_4.setTitle(_translate("MainWindow", "实时语音转写"))
        self.start_but.setText(_translate("MainWindow", "start"))
        self.stop_but.setText(_translate("MainWindow", "stop"))
        self.play_but.setText(_translate("MainWindow", "playback"))
        self.keyword_but.setText(_translate("MainWindow", "keyword"))

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())